// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: borrow.proto

package borrow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BorrowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book string `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *BorrowReq) Reset() {
	*x = BorrowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_borrow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowReq) ProtoMessage() {}

func (x *BorrowReq) ProtoReflect() protoreflect.Message {
	mi := &file_borrow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowReq.ProtoReflect.Descriptor instead.
func (*BorrowReq) Descriptor() ([]byte, []int) {
	return file_borrow_proto_rawDescGZIP(), []int{0}
}

func (x *BorrowReq) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

type BorrowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book      string                 `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *BorrowResp) Reset() {
	*x = BorrowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_borrow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowResp) ProtoMessage() {}

func (x *BorrowResp) ProtoReflect() protoreflect.Message {
	mi := &file_borrow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowResp.ProtoReflect.Descriptor instead.
func (*BorrowResp) Descriptor() ([]byte, []int) {
	return file_borrow_proto_rawDescGZIP(), []int{1}
}

func (x *BorrowResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BorrowResp) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *BorrowResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BorrowResp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_borrow_proto protoreflect.FileDescriptor

var file_borrow_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x09, 0x62, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0xa6, 0x01, 0x0a, 0x0a, 0x62, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x32, 0x69, 0x0a, 0x08, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x2c, 0x0a,
	0x03, 0x61, 0x64, 0x64, 0x12, 0x11, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x62, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e,
	0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_borrow_proto_rawDescOnce sync.Once
	file_borrow_proto_rawDescData = file_borrow_proto_rawDesc
)

func file_borrow_proto_rawDescGZIP() []byte {
	file_borrow_proto_rawDescOnce.Do(func() {
		file_borrow_proto_rawDescData = protoimpl.X.CompressGZIP(file_borrow_proto_rawDescData)
	})
	return file_borrow_proto_rawDescData
}

var file_borrow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_borrow_proto_goTypes = []interface{}{
	(*BorrowReq)(nil),             // 0: borrow.borrowReq
	(*BorrowResp)(nil),            // 1: borrow.borrowResp
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_borrow_proto_depIdxs = []int32{
	2, // 0: borrow.borrowResp.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: borrow.borrowResp.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: borrow.borrower.add:input_type -> borrow.borrowReq
	0, // 3: borrow.borrower.list:input_type -> borrow.borrowReq
	1, // 4: borrow.borrower.add:output_type -> borrow.borrowResp
	1, // 5: borrow.borrower.list:output_type -> borrow.borrowResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_borrow_proto_init() }
func file_borrow_proto_init() {
	if File_borrow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_borrow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_borrow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_borrow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_borrow_proto_goTypes,
		DependencyIndexes: file_borrow_proto_depIdxs,
		MessageInfos:      file_borrow_proto_msgTypes,
	}.Build()
	File_borrow_proto = out.File
	file_borrow_proto_rawDesc = nil
	file_borrow_proto_goTypes = nil
	file_borrow_proto_depIdxs = nil
}
