version: "3.9"

services:
  #搜集kafka业务日志、存储prometheus监控数据
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: elasticsearch
    user: root
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Shanghai
    networks:
      - bookstore_net
  postgres:
    image: postgres:latest
    container_name: postgres
    privileged: true
    restart: always
    ports:
      - "55432:5432"
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: xiaohuozhi2022.
      POSTGRES_HOST_AUTH_METHOD: password
      LANG: en_US.utf8
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    networks:
      - bookstore_net
  redis:
    image: redis:latest
    container_name: redis
    privileged: true
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass WGlhb2h1b3poaTIwMjIu  --appendonly yes"
    ports:
      - "6379:6379"
    networks:
      - bookstore_net
  #jaeger链路追踪 — Jaeger for tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - LOG_LEVEL=debug
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    networks:
      - bookstore_net
    #    command: sh -c './wait-for.sh elasticsearch:9200 -t 60 -- echo "ES已启动"'
    depends_on:
      - elasticsearch

networks:
  bookstore_net:
    driver: bridge