// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"bookstore/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: AddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/check",
				Handler: CheckHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/borrow",
				Handler: BorrowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/borrow/list",
				Handler: BorrowHistoryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/book"),
	)
}
